# Generated by Django 4.1.7 on 2023-07-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField(null=True)),
            ],
        ),
    ]
