# Generated by Django 4.1.7 on 2023-07-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
